#!/bin/sh
 RESET ="\033[0m"
 PURPLE ="\033[0;34m"
#  BLACK ="\033[0;30m"
#  RED ="\033[0;31m"
#  GREEN ="\033[0;32m"
#  YELLOW ="\033[0;33m"
#  PINK ="\033[0;35m"
#  SKY ="\033[0;36m"

echo "                                                                                                         "
echo "                                                                                                X        "
echo "                                                                                               X X       "
echo "                                                                                              X   X      "
echo "                                                                                             z     X     "
echo "                                                                                            x       x    "
echo "                                                                                           x        X    "
echo "                                                                                          ()         x   "
echo "                                                                                          X          X   "
echo "                                                                                                     X   "
echo "${PURPLE}   X       X    XXX   XXX     XXX   XXX   XXX S X X   XXX     XXX   XXX X X   XXX       XXX${RESET}          X   "
echo "  XXX     XXX   I I   X X X   X X   I I   S S         X X     X X   X E       X L       X L          X   "
echo "  X X M M X X   I I   X X  X  X X   I I   XXX S XXX   X X H H X X   X E E X   X L       X L          x   "
echo "  X X     X X   I I   X X   X X X   I I         S S   X X     X X   X E       X L       X L         X    "
echo "  XXX     XXX   XXX   XXX     XXX   XXX   X X S XXX   XXX     XXX   XXX X X   XXX X X   XXX X X     *    "
echo "                                                                                                    a    "
echo "                                + X X X X X X X X                                   X               X    "
echo "                            w X X X X X X X X X X X 2                              X k          X X      "
echo "                      v   X X X X X X X X X X X X X X X X @                       X             X X      "
echo "                      X X X X X X X X X X X X X X X X X X X X                     X             O @      "
echo "                  X X X X X X X X X   X X X X X X X X X X X X X @                j                X      "
echo "                  X X X X X X           X X X X X X X         X X @             xx                X      "
echo "              X X X X X X +               X X X X X X           X Xx            x               q z      "
echo "              X X X X X X                   X X X X X             Xxx          X %              X        "
echo "            X X X X X X                     f X X X 6               X          X                X        "
echo "            X X X X X X                       X X X _       R X     O X      X                M 2        "
echo "          + X X X X X           X + X         X X X ^           X     X      X                X          "
echo "          X X X X X X         v     X x       X X X         J w X     X     X H               X          "
echo "          X X X X X X         v b r   y      x      x x     X X X      P X  K X               X          "
echo "          X X X X X X         W X     v   x x          x x   x x       x X X X                P          "
echo "        X X X X X X +           vx xX       x x x x x x                 X X V               X            "
echo "        X X X X X X X                          X X x                    q X X n             X            "
echo "        X X X X X X X                                                    X P X X X +        X            "
echo "        X X X X X X X                                                    X    r     Q X X X C            "
# echo "        X X X X X X X J                                                   X T X '       X                "
# echo "      v X X X X X X X X                                                   X p         X t                "
# echo "      v   X X X X X X X X                                                       j X X T                  "
# echo "      + X X X X X X X X X X   {                                             X G X X X H                  "
# echo "      ] X X X X X X X X X X X X                                           + X X X X X Y                  "
# echo "      ( X X X X X X X X X X X X                                           3 X X X X                      "
# echo "      ! X X X X X X X X X X X @                                           a X ) X X X                    "
# echo "      T X X X b X X X X X X X                                             z X     X                      "
# echo "      N X X X / X X X X X X X                                             B X   S 0                      "
# echo "      < X X X X X X X X a X X                                             S X   X                        "
# echo "      X X X X X   X X   F X X                                             c X   X                        "
# echo "    X X X X X X X M X c X X                                               4 X   X                        "
# echo "  X X X X X X X X X   X X X X                                             X X   X                        "
# echo "b X X X X X X X X X X X X X X                                             X f   X                        "
# echo "+ X X X X X X X X X X X X X X                                           E X     f                        "
# echo "8 X X X X X X X X X X X X X X                                             X X X                          "
# echo "  X X X X X X X X X X X X X X                                           X X                              "
# echo "      X X X X X X X X X X X X A                                   y     X X                              "
# echo "        a X X X X X X X X X X 6       [ X                       X       + X                              "
# echo "            v X X X X X X X               V i         % K   X X [ ) X X X X                              "
# echo "                    I q X                   T X     X X X X X X X X {                                    "
# echo "                        X       X c       X X X [ v                                                      "
# echo "                        +  ++ 1 z X X X X C                                                              "
# echo "                                                                                                        "

#  X       X    X X   X X      X X   X X   X X S X X   X X     X X   X X X X   X X       X X    
# X X     X X   I I   X X X    X X   I I   S S         X X     X X   X E       X L       X L    
# X X M M X X   I I   X X  X   X X   I I   X X S X X   X X H H X X   X E E X   X L       X L    
# X X     X X   I I   X X    X X X   I I         S S   X X     X X   X E       X L       X L    
# X X     X X   X X   X X      X X   X X   X X S X X   X X     X X   X X X X   X X X X   X X X X